### ISSUE TITLE
Implement Google Analytics and Tag Manager

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-guide#46]
# What

Add Google Analytics and Tag Manager. This will require a [cookie banner](https://design-system.service.gov.uk/components/cookie-banner/) and [cookie page](https://design-system.service.gov.uk/patterns/cookies-page/).

# Why

To track performance of the site

# Done when

- [x] Cookie banner appears if user hasn't selected an option
- [x] Cookie banner does not appear if user has selected an option
- [x] If user has not opted in, no cookies are set, no analytics recorded
- [x] If user has opted in, cookie is set and analytics are recorded
- [x] Cookie page

**Comment by nnagewad** [comment]
PR #72 has merged into main.
