### ISSUE TITLE
Add Open Graph (OG) image similar to Design System

### ISSUE THREAD

**Issue by calumryan** [alphagov/govuk-design-guide#69]
Add open graph image for better visibility sharing on social media, Slack, etc.

Design System example:
![Screenshot of OG image, title and description](https://github.com/user-attachments/assets/82735fb4-64fa-4ab4-a96e-3b694bece8a7)

**Comment by nnagewad** [comment]
Dude good shout. Was wondering should we use the Lego piece as the icon?

**Comment by calumryan** [comment]
Yes that seems a like a suitable choice

**Comment by nnagewad** [comment]
PR was created and merged.
