### ISSUE TITLE
Update Single Page Notify Button

### ISSUE THREAD

**Issue by nnagewad** [alphagov/govuk-design-guide#88]
When documenting in [Google Doc](https://docs.google.com/document/d/1Fb6Vv-QS5tuYqhCYBcpGIaTNt4zDBeBMznz-7Nch-lE/edit?tab=t.0#heading=h.3jrh12ndfym) we had logged some issues and inconsistencies that will need adding once we have decided how to do that.

**Comment by ChristineWuerth** [comment]
If you don't find it in main, find it in this pull request: https://github.com/alphagov/govuk-design-guide/pull/80
